### ISSUE TITLE
survey

### ISSUE THREAD

**Issue by kcagdass** [kcagdass/WORKS#1]
freecodecamp-kursu Build a Survey Form-free için

**Comment by kburakozdemir** [comment]
yeterince bilgi verir misin? ne için yardım istiyorsun? tanımı daraltman gerekiyor.

**Comment by kcagdass** [comment]
read.me yi düzelttim biraz, labelleri karıştırırken help wanted a da basmışım.

**Comment by kburakozdemir** [comment]
@kcagdass kapatabilirsin o zaman issue'yu
