### ISSUE TITLE
lokal git kullanımı

### ISSUE THREAD

**Issue by kburakozdemir** [kcagdass/WORKS#2]
doğru anlıyorsam eğer işaretli commit'ler doğrudan GitHub'da yapılmışlar. 

![image](https://user-images.githubusercontent.com/1656836/46798371-6af51f00-cd5a-11e8-8243-b6525bb9bceb.png)

bunun yerine git tabanlı iş akışlarını ve IDE ve terminal kullanımını geliştirmek adına tarayıcıda yapmak yerine lokalde yapıp, push etmek daha uygun olmaz mı?

```bash
# işi yap
# sonra o iş paketine ait olan dosyaları belirle
git status
# sonra belirlediklerini commit etmek üzere hazırla
git add _filename1_
git add _filename2_
# sonra yaptığın işin  daha sonra anlaşılabileceği
# anlamlı bir mesaj ile commit et
git commit -m "işin anlaşılacağı bir mesaj"
# sonra onları GitHub'a push et
git push
```

**Comment by kcagdass** [comment]
evet github üzerinden yapıldı. git üzerinden yapılabildiğini gitlap a baktıktan sonra anladım.
